// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Header(Props) {
  var text = Props.text;
  return React.createElement("div", {
              className: "flex items-center mx-auto w-fit h-36"
            }, React.createElement("p", {
                  className: "text-2xl h-fit font-extrabold tracking-wide"
                }, text));
}

var make = Header;

export {
  make ,
  
}
/* react Not a pure module */
