// Generated by ReScript, PLEASE EDIT WITH CARE

import * as List from "rescript/lib/es6/list.js";
import * as Table from "./Table/Table.js";
import * as React from "react";
import * as Header from "./Header/Header.js";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Router from "next/router";

function App$default(Props) {
  var data = Props.data;
  var query = List.find_opt((function (q) {
          return Js_dict.get(Router.useRouter().query, q) !== undefined;
        }), {
        hd: "phone",
        tl: {
          hd: "brand",
          tl: {
            hd: "priceRange",
            tl: /* [] */0
          }
        }
      });
  var headerText = query !== undefined ? query : "Mobile History Rating";
  return React.createElement("div", undefined, React.createElement(Header.make, {
                  text: headerText
                }), React.createElement(Table.make, {
                  phones: data
                }));
}

var $$default = App$default;

export {
  $$default ,
  $$default as default,
  
}
/* Table Not a pure module */
