// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";

function Table(Props) {
  var phones = Props.phones;
  var mapPhonesToTableRows = function (param) {
    var price_range = param.price_range;
    var model = param.model;
    var brand = param.brand;
    var priceRangeSymbol = price_range === 2 ? "$$" : (
        price_range === 3 ? "$$$" : (
            price_range === 4 ? "$$$$" : (
                price_range === 5 ? "$$$$$" : "$"
              )
          )
      );
    var priceRangeString = price_range === 2 ? "2" : (
        price_range === 3 ? "3" : (
            price_range === 4 ? "4" : (
                price_range === 5 ? "5" : "1"
              )
          )
      );
    var tdClassName = "border text-center px-8 py-4";
    return React.createElement("tr", {
                key: param.id
              }, React.createElement("td", {
                    className: tdClassName
                  }, React.createElement(Link, {
                        href: "/brands/" + brand,
                        children: React.createElement("a", undefined, brand)
                      })), React.createElement("td", {
                    className: tdClassName
                  }, React.createElement(Link, {
                        href: "/phones/" + model,
                        children: React.createElement("a", undefined, model)
                      })), React.createElement("td", {
                    className: tdClassName
                  }, React.createElement(Link, {
                        href: "/price-ranges/" + priceRangeString,
                        children: React.createElement("a", undefined, priceRangeSymbol)
                      })));
  };
  return React.createElement("div", {
              className: "flex justify-center w-full"
            }, React.createElement("table", {
                  className: "shadow-lg bg-white"
                }, React.createElement("thead", undefined, React.createElement("tr", undefined, React.createElement("th", {
                              className: "bg-blue-100 border text-center px-8 py-4"
                            }, "Brand"), React.createElement("th", {
                              className: "bg-blue-100 border text-center px-8 py-4"
                            }, "Model"), React.createElement("th", {
                              className: "bg-blue-100 border text-center px-8 py-4"
                            }, "Price Range"))), React.createElement("tbody", undefined, phones.map(mapPhonesToTableRows))));
}

var make = Table;

export {
  make ,
  
}
/* react Not a pure module */
